  # Increase the spacing between horizontal bars in equals sign
  [ident.ident]
  equalHorizontalBarHeight = 0.5      # Default might be around 0.1
  equalHorizontalBarDistance = 0.60    # Default might be around 0.2

  # These are the specific settings for the eqeqeq ligature
  [ident.lig.fc]
  equalHorizontalBarDistance = 0.75

  [ident.lig.cc]
  equalHorizontalBarDistance = 0.75

  [ident.lig.cf]
  equalHorizontalBarDistance = 0.75
