[buildPlans.IosevkaBigEquals]
family = "Iosevka BigEquals"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
buildTextureFeature = true
# parameters = "params/spaced-equals.toml"

[buildPlans.IosevkaBigEquals.weights.Regular]
shape = 400
menu = 400
css = 400

# [buildPlans.IosevkaBigEquals.parameters]
# # # Increase the triple-equals bar spacing
# # # You would adjust from 1.5 (default) to your desired value
# identHalfSpaceMultiplier = 2.0


[buildPlans.IosevkaBigEquals.metricOverride]
leading = 1450

[buildPlans.IosevkaBigEquals.variants]
inherits = "ss10"

[buildPlans.IosevkaBigEquals.variants.design]
zero = "slashed" 
asterisk = "penta-low"
underscore = "high"
tilde = "low"
# capital-w = "straight-serifless"
# capital-w = "rounded-vertical-sides-serifless"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
dollar = "through"

# [buildPlans.IosevkaBigEquals.weights.Light]
# shape = 300
# menu = 300
# css = 300

# [buildPlans.IosevkaBigEquals.weights.Regular]
# shape = 400
# menu = 400
# css = 400

# [buildPlans.IosevkaBigEquals.weights.SemiBold]
# shape = 600
# menu = 600
# css = 600

[buildPlans.IosevkaBigEquals.ligations]
inherits = "javascript"
arrow-l = true
arrow-lr = true
arrow-r = true
bar-triggers-op-centering = true
center-op-influence-colon = true
center-op-influence-dot = true
center-op-trigger-angle-inside = true
center-op-trigger-angle-outside = true
center-op-trigger-bar-l = true
center-op-trigger-bar-r = true
center-op-trigger-equal-l = true
center-op-trigger-equal-r = true
center-op-trigger-plus-minus-l = true
center-op-trigger-plus-minus-r = true
center-ops = true
dot-as-operator = true
eqeqeq = true
exeq = false
eqeq = false
exeqeq = true
gteq = true
hash-hash = true
html-comment = true
kern-bars = true
kern-dotty = true
llgg = true
llggeq = true
lteq = true
minus-minus-minus = true
plus-plus-plus = true
slash-asterisk = true
trig = true
underscore-underscore-underscore = true
